In [1]:
import pandas as pd

In [19]:
df = pd.read_csv('tested.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

# Checking for null values and duplicate values

In [20]:
df.drop_duplicates(inplace=True)
df.shape  # No duplicates

(418, 12)

In [21]:
df.isna().sum() # Lot of null values out here in age,cabin and fare

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [22]:
df['Age'].fillna(df['Age'].mean(),inplace=True)

In [23]:
df['Fare'].fillna(df['Fare'].mode(),inplace=True)

In [24]:
df.drop(columns={'Cabin','Name','Embarked','Ticket'},inplace=True)

In [25]:
df

     PassengerId  Survived  Pclass     Sex       Age  SibSp  Parch      Fare
0            892         0       3    male  34.50000      0      0    7.8292
1            893         1       3  female  47.00000      1      0    7.0000
2            894         0       2    male  62.00000      0      0    9.6875
3            895         0       3    male  27.00000      0      0    8.6625
4            896         1       3  female  22.00000      1      1   12.2875
..           ...       ...     ...     ...       ...    ...    ...       ...
413         1305         0       3    male  30.27259      0      0    8.0500
414         1306         1       1  female  39.00000      0      0  108.9000
415         1307         0       3    male  38.50000      0      0    7.2500
416         1308         0       3    male  30.27259      0      0    8.0500
417         1309         0       3    male  30.27259      1      1   22.3583

[418 rows x 8 columns]

In [32]:
df.groupby('Sex')['Survived'].count() # total male 266 and female 152

Sex
female    152
male      266
Name: Survived, dtype: int64

In [36]:
df.groupby('Sex')['Survived'].sum() # only females survived

Sex
female    152
male        0
Name: Survived, dtype: int64

In [41]:
df[df['Age'] < 18].groupby('Age')['Survived'].sum().sum()

17

In [35]:
df.groupby('Age'>18)['Survived'].count()

TypeError: '>' not supported between instances of 'str' and 'int'